version: '3.8'

services:
  webapp:
    image: lukatrt/projet_2_roues:latest
    container_name: commande_hoverboard
    ports:
      - "9999:9999"
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
